name: 'VSCDC smoke test'
inputs:
  definition:
    description: 'Definition to test'
    required: true
    default: 'debian'
  user:
    description: 'User in container image to use for smoke test'
    required: true
    default: 'vscode'

jobs:
  build-and-test:
    name: Build and test images
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v2

    - name: Build image
      id: build_image
      run: .github/actions/smoke-test/build.sh ${{ inputs.definition }}

    - name: Test image
      id: test_image
      shell: bash
      run: chmod +x .github/actions/smoke-test/test.sh && .github/actions/smoke-test/test.sh  ${{ inputs.definition }} ${{ inputs.user }}
