name: Build and push images

on: 
  push:
    tags:
    - 'v*'

jobs:
  build-and-push:
    name: Build and push images
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        page: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        page-total: [11]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - name: Get tag name
      id: get_tag_name  
      run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

    - name: Azure CLI login
      id: az_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_ACR_CREDS }}

    - name: Build and push
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_BASE_PATH: ${{ secrets.REGISTRY_BASE_PATH }}
        STUB_REGISTRY: ${{ secrets.STUB_REGISTRY }}
        STUB_REGISTRY_BASE_PATH: ${{ secrets.STUB_REGISTRY_BASE_PATH }}
      run: |
        set -e

        # ACR login
        ACR_REGISTRY_NAME=$(echo "$REGISTRY" | grep -oP '(.+)(?=\.azurecr\.io)')
        az acr login --name $ACR_REGISTRY_NAME

        # Build and push images
        yarn install
        npm install -g @devcontainers/cli@0.8.0
        build/vscdc push  --page ${{ matrix.page }} \
                          --pageTotal ${{ matrix.page-total }} \
                          --release ${{ steps.get_tag_name.outputs.tag }} \
                          --github-repo ${{ github.repository }} \
                          --registry "$REGISTRY" \
                          --registry-path "$REGISTRY_BASE_PATH" \
                          --stub-registry "$STUB_REGISTRY" \
                          --stub-registry-path "$STUB_REGISTRY_BASE_PATH"

  image-info:
    name: Trigger info extraction
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

    - name: Trigger image info file generation
      uses: devcontainers/images/.github/workflows/version-history.yml@main
      with:
        release: ${{ steps.get_tag_name.outputs.tag }}
        cg: "false"
        push: "true"
        overwrite: "false"
      secrets: inherit
