name: Build and push images

on: 
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push images
    strategy:
      matrix:
        page: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        page-total: [11]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - name: Azure CLI login
      id: az_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_ACR_CREDS }}

    - name: Build and push
      id: build_and_push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        set -e

        # ACR login
        ACR_REGISTRY_NAME=$(echo ${{ secrets.REGISTRY }} | grep -oP '(.+)(?=\.azurecr\.io)')
        az acr login --name $ACR_REGISTRY_NAME

        # Build and push images
        yarn install
        npm install -g @devcontainers/cli
        build/vscdc push  --page ${{ matrix.page }} \
                          --pageTotal ${{ matrix.page-total }} \
                          --release v0.0.1 \
                          --github-repo ${{ github.repository }} \
                          --registry ${{ secrets.REGISTRY }} \
                          --registry-path ${{ secrets.REGISTRY_BASE_PATH }} \
                          --stub-registry ${{ secrets.STUB_REGISTRY }} \
                          --stub-registry-path ${{ secrets.STUB_REGISTRY_BASE_PATH }}

  image-info:
    name: Trigger info extraction
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      
    - name: Trigger image info file generation 
      id: image-info
      run: |
        set -e
        echo '(*) Triggering CG manifest and image history generation using workflow_dispatch'

        # Use alternate GitHub token due to https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
        curl -X POST \
          -H "Authorization: token ${{ secrets.ALTERNATE_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/version-history.yml/dispatches \
          --data "{\"ref\": \"main\", \"inputs\": {\"release\": \"v0.0.1\", \"cg\": \"false\", \"push\": \"true\", \"overwrite\": \"false\"}"
