name: Smoke test "python" build

on: 
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'src/python/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/python/**'
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: python
        image: mcr.microsoft.com/vscode/devcontainers/python:dev-3
        user: vscode
