name: Smoke test "cpp" build

on: 
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'src/cpp/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/cpp/**'
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: cpp
        image: vsc-cpp
        user: vscode
