name: Smoke test "dotnet" build

on: 
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'src/dotnet/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/dotnet/**'
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      id: smoke_test
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      uses: ./.github/actions/smoke-test
      with:
        definition: dotnet
        user: vscode
