name: Smoke test "alpine" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/alpine/**
      - .github/workflows/smoke-alpine.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
      
    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: alpine
        image: mcr.microsoft.com/devcontainers/base:dev-alpine
        user: vscode
